// <auto-generated />
using Dogshouseservice.Infrastructure.Dogs.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dogshouseservice.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241028122108_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Dogshouseservice.Domain.Dogs.Dog", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TailLength")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("Name");

                    b.ToTable("Dogs");

                    b.HasData(
                        new
                        {
                            Name = "Neo",
                            Color = "red & amber",
                            TailLength = 22,
                            Weight = 32
                        },
                        new
                        {
                            Name = "Jessy",
                            Color = "black & white",
                            TailLength = 7,
                            Weight = 14
                        },
                        new
                        {
                            Name = "Buddy",
                            Color = "brown",
                            TailLength = 10,
                            Weight = 20
                        },
                        new
                        {
                            Name = "Max",
                            Color = "black",
                            TailLength = 8,
                            Weight = 18
                        },
                        new
                        {
                            Name = "Charlie",
                            Color = "golden",
                            TailLength = 15,
                            Weight = 25
                        },
                        new
                        {
                            Name = "Rocky",
                            Color = "gray",
                            TailLength = 12,
                            Weight = 24
                        },
                        new
                        {
                            Name = "Bella",
                            Color = "white",
                            TailLength = 9,
                            Weight = 17
                        },
                        new
                        {
                            Name = "Lucy",
                            Color = "cream",
                            TailLength = 13,
                            Weight = 23
                        },
                        new
                        {
                            Name = "Daisy",
                            Color = "black & tan",
                            TailLength = 16,
                            Weight = 26
                        },
                        new
                        {
                            Name = "Molly",
                            Color = "chocolate",
                            TailLength = 11,
                            Weight = 19
                        },
                        new
                        {
                            Name = "Bailey",
                            Color = "blue & white",
                            TailLength = 14,
                            Weight = 22
                        },
                        new
                        {
                            Name = "Maggie",
                            Color = "brindle",
                            TailLength = 18,
                            Weight = 27
                        },
                        new
                        {
                            Name = "Sophie",
                            Color = "red",
                            TailLength = 10,
                            Weight = 20
                        },
                        new
                        {
                            Name = "Sadie",
                            Color = "black",
                            TailLength = 7,
                            Weight = 15
                        },
                        new
                        {
                            Name = "Lola",
                            Color = "golden",
                            TailLength = 20,
                            Weight = 30
                        },
                        new
                        {
                            Name = "Zoe",
                            Color = "tan",
                            TailLength = 12,
                            Weight = 22
                        },
                        new
                        {
                            Name = "Cooper",
                            Color = "gray",
                            TailLength = 15,
                            Weight = 28
                        },
                        new
                        {
                            Name = "Buster",
                            Color = "white",
                            TailLength = 9,
                            Weight = 16
                        },
                        new
                        {
                            Name = "Oscar",
                            Color = "cream",
                            TailLength = 14,
                            Weight = 24
                        },
                        new
                        {
                            Name = "Teddy",
                            Color = "black & white",
                            TailLength = 17,
                            Weight = 29
                        },
                        new
                        {
                            Name = "Bentley",
                            Color = "brown",
                            TailLength = 8,
                            Weight = 18
                        },
                        new
                        {
                            Name = "Roxy",
                            Color = "blue",
                            TailLength = 11,
                            Weight = 21
                        },
                        new
                        {
                            Name = "Harley",
                            Color = "black & tan",
                            TailLength = 12,
                            Weight = 22
                        },
                        new
                        {
                            Name = "Chloe",
                            Color = "brindle",
                            TailLength = 19,
                            Weight = 31
                        },
                        new
                        {
                            Name = "Luna",
                            Color = "red & white",
                            TailLength = 21,
                            Weight = 32
                        },
                        new
                        {
                            Name = "Leo",
                            Color = "black",
                            TailLength = 9,
                            Weight = 17
                        },
                        new
                        {
                            Name = "Jack",
                            Color = "golden",
                            TailLength = 13,
                            Weight = 23
                        },
                        new
                        {
                            Name = "Finn",
                            Color = "gray",
                            TailLength = 10,
                            Weight = 20
                        },
                        new
                        {
                            Name = "Zeus",
                            Color = "white & tan",
                            TailLength = 16,
                            Weight = 25
                        },
                        new
                        {
                            Name = "Hank",
                            Color = "chocolate",
                            TailLength = 11,
                            Weight = 21
                        },
                        new
                        {
                            Name = "Gus",
                            Color = "blue & white",
                            TailLength = 18,
                            Weight = 27
                        },
                        new
                        {
                            Name = "Riley",
                            Color = "black & red",
                            TailLength = 14,
                            Weight = 22
                        },
                        new
                        {
                            Name = "Scout",
                            Color = "tan & white",
                            TailLength = 12,
                            Weight = 19
                        },
                        new
                        {
                            Name = "Oliver",
                            Color = "black",
                            TailLength = 20,
                            Weight = 30
                        },
                        new
                        {
                            Name = "Dexter",
                            Color = "golden",
                            TailLength = 15,
                            Weight = 24
                        },
                        new
                        {
                            Name = "Sam",
                            Color = "gray",
                            TailLength = 7,
                            Weight = 14
                        },
                        new
                        {
                            Name = "Rusty",
                            Color = "brindle",
                            TailLength = 10,
                            Weight = 20
                        },
                        new
                        {
                            Name = "Tank",
                            Color = "red",
                            TailLength = 13,
                            Weight = 23
                        },
                        new
                        {
                            Name = "Jasper",
                            Color = "black & white",
                            TailLength = 17,
                            Weight = 28
                        },
                        new
                        {
                            Name = "Boomer",
                            Color = "white",
                            TailLength = 8,
                            Weight = 16
                        },
                        new
                        {
                            Name = "Chase",
                            Color = "cream",
                            TailLength = 11,
                            Weight = 21
                        },
                        new
                        {
                            Name = "Bandit",
                            Color = "tan",
                            TailLength = 9,
                            Weight = 18
                        },
                        new
                        {
                            Name = "Ace",
                            Color = "blue",
                            TailLength = 16,
                            Weight = 26
                        },
                        new
                        {
                            Name = "Simba",
                            Color = "black & tan",
                            TailLength = 19,
                            Weight = 29
                        },
                        new
                        {
                            Name = "Bruce",
                            Color = "chocolate",
                            TailLength = 22,
                            Weight = 33
                        },
                        new
                        {
                            Name = "Thor",
                            Color = "gray",
                            TailLength = 14,
                            Weight = 24
                        },
                        new
                        {
                            Name = "Bruno",
                            Color = "black",
                            TailLength = 7,
                            Weight = 15
                        },
                        new
                        {
                            Name = "Koda",
                            Color = "golden",
                            TailLength = 18,
                            Weight = 28
                        },
                        new
                        {
                            Name = "Marley",
                            Color = "white & red",
                            TailLength = 10,
                            Weight = 19
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
